trigger:
  branches:
    include:
      - "*"

parameters:
  - name: target
    displayName: "Target to build and test"
    type: string
    default: all
    values:
      - all
      - inspectra-webserver
      - inspectra-os

stages:
  - stage: InspectraWebserver
    displayName: "Inspectra Webserver Compliance"
    condition: or(eq('${{parameters.target}}', 'all'), eq('${{parameters.target}}', 'inspectra-webserver'))
    jobs:
      - job: BuildAndTestWebserver
        displayName: "Build and Run inspectra-webserver"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              echo "Setting up directory structure..."
              mkdir -p $(Build.ArtifactStagingDirectory)/webserver_reports
              mkdir -p $(Build.SourcesDirectory)/inspectra-webserver/controls
              mkdir -p $(Build.SourcesDirectory)/inspectra-webserver/test
              chmod -R 777 $(Build.ArtifactStagingDirectory)/webserver_reports
            displayName: "Prepare directories"

          - task: Docker@2
            displayName: "Build inspectra-webserver Docker image"
            inputs:
              command: build
              Dockerfile: inspectra-webserver/Dockerfile
              tags: |
                inspectra-webserver:$(Build.BuildId)
              buildContext: $(Build.SourcesDirectory)/inspectra-webserver
              repository: inspectra-webserver

          - script: |
              echo "Running inspectra-webserver compliance checks..."
              
              # Debug directory structure
              echo "Available test configs:"
              find $(Build.SourcesDirectory)/inspectra-webserver/test -type f | sort
              
              # Run Docker with all required volume mounts
              docker run --rm --user root \
                -v $(Build.SourcesDirectory)/inspectra-webserver/controls:/app/controls \
                -v $(Build.SourcesDirectory)/inspectra-webserver/test:/app/test \
                -v $(Build.SourcesDirectory)/inspectra-webserver/src:/app/src \
                -v $(Build.ArtifactStagingDirectory)/webserver_reports:/app/reports \
                -e CHEF_LICENSE=accept \
                -e INSPEC_LICENSE=accept \
                inspectra-webserver:$(Build.BuildId) bash -c "
                  # Fix permissions
                  chmod -R 777 /app/reports /app/controls /app/test
                  
                  # Check InSpec installation
                  echo 'InSpec version:'
                  inspec --version
                  
                  # Run the profile script
                  /usr/local/bin/run_all_profiles.sh
                "
                
              # Show generated reports
              echo "Generated reports:"
              find $(Build.ArtifactStagingDirectory)/webserver_reports -type f | sort
            displayName: "Run inspectra-webserver compliance checks"

          - publish: $(Build.ArtifactStagingDirectory)/webserver_reports
            artifact: webserver_reports
            displayName: "Publish webserver compliance reports"

  - stage: InspectraOS
    displayName: "Inspectra OS Compliance"
    condition: or(eq('${{parameters.target}}', 'all'), eq('${{parameters.target}}', 'inspectra-os'))
    jobs:
      - job: BuildAndTestOS
        displayName: "Build and Run inspectra-os"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              echo "Setting up directory structure..."
              mkdir -p $(Build.ArtifactStagingDirectory)/os_reports
              chmod -R 777 $(Build.ArtifactStagingDirectory)/os_reports
            displayName: "Prepare directories"

          - task: Docker@2
            displayName: "Build inspectra-os Docker image"
            inputs:
              command: build
              Dockerfile: inspectra-os/Dockerfile
              tags: |
                inspectra-os:$(Build.BuildId)
              buildContext: $(Build.SourcesDirectory)/inspectra-os
              repository: inspectra-os

          - script: |
              echo "Running inspectra-os compliance checks..."
              
              # Run Docker with all required volume mounts
              docker run --rm --user root \
                -v $(Build.SourcesDirectory)/inspectra-os/src:/app/src \
                -v $(Build.ArtifactStagingDirectory)/os_reports:/app/reports \
                -e CHEF_LICENSE=accept \
                -e INSPEC_LICENSE=accept \
                inspectra-os:$(Build.BuildId) bash -c "
                  # Fix permissions
                  chmod -R 777 /app/reports
                  
                  # Check InSpec installation
                  echo 'InSpec version:'
                  inspec --version
                  
                  # Run the profile script
                  /app/run_all_profiles.sh
                "
                
              # Show generated reports
              echo "Generated reports:"
              find $(Build.ArtifactStagingDirectory)/os_reports -type f | sort
            displayName: "Run inspectra-os compliance checks"

          - publish: $(Build.ArtifactStagingDirectory)/os_reports
            artifact: os_reports
            displayName: "Publish OS compliance reports"
